server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/defimon/config-repo.git}
          clone-on-start: true
          force-pull: true
          default-label: main
        native:
          search-locations: classpath:/config
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,refresh
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.defimon: DEBUG
    org.springframework.cloud.config: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---
spring:
  profiles: dev

logging:
  level:
    com.defimon: DEBUG
    org.springframework.cloud.config: DEBUG

---
spring:
  profiles: prod

logging:
  level:
    com.defimon: INFO
    org.springframework.cloud.config: INFO
